<h1 align="center">
    Section 2. Matrix Algebra
</h1>

## **1. Một số khái niệm cơ bản về ma trận** 

#### Các phép tính cơ bản trên ma trận

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

#### Exercise 11. Phép nhân ma trận - Multiple

In [2]:
import numpy as np

A =np.array([[-1, 3],[4, 2]])
B =np.array([[4, -3],[1, -2], [-2, 0]])
C =np.array([[5, -4, 2]])

print(5*A) 
print(B@A)
print(A.T @ B.T)
print(C @ B)

[[-5 15]
 [20 10]]
[[-16   6]
 [ -9  -1]
 [  2  -6]]
[[-16  -9   2]
 [  6  -1  -6]]
[[12 -7]]


#### Exercise 12. Phép chuyển vị - Transpose

In [3]:
from numpy.linalg import inv
A =np.array([[2, 1], [1, 3]])
B =np.array([[1, 4, 2], [5, 0 ,3]])
C =np.array([[1, 4], [3, 2]])

print(A.T.T == A)
print(inv(C.T))
print(inv(C).T)
print((A @ C).T == C.T @ A.T)

[[ True  True]
 [ True  True]]
[[-0.2  0.3]
 [ 0.4 -0.1]]
[[-0.2  0.3]
 [ 0.4 -0.1]]
[[ True  True]
 [ True  True]]


### ***1.1. Ma trận trực giao (Orthogonal Matrix)***

- **Định nghĩa:** Một ma trận vuông $Q$ được gọi là ma trận trực giao nếu thỏa mãn điều kiện:
  $$QQ' = Q'Q = I \quad \text{hay} \quad Q' = Q^{-1}$$
- **Tính chất:** Các dòng (hoặc các cột) của ma trận trực giao là các véc tơ có độ dài bằng $1$ (đã chuẩn hóa) và đôi một vuông góc với nhau. Tức là, gọi $q_i$ là dòng thứ $i$, ta có $q_i'q_i = 1$ và $q_i'q_j = 0$ (với $i \neq j$).

#### Exercise 14. Kiểm tra ma trận trực giao

In [4]:
# Khai báo ma trận Q
Q = np.array([
    [5/13, 12/13],
    [-12/13,  5/13]
])

# Tính Q_T * Q
Q_T = Q.T
product = np.dot(Q_T, Q)

# In kết quả
print("Ma trận Q:")
print(Q)
print("\nMa trận chuyển vị Q^T:")
print(Q_T)
print("\nKết quả Q^T * Q:")
print(np.round(product, 8)) # Làm tròn để tránh sai số số thực

# Kiểm tra điều kiện ma trận đơn vị
is_orthogonal = np.allclose(product, np.eye(2))
print(f"\nQ có phải ma trận trực giao không? -> {is_orthogonal}")

Ma trận Q:
[[ 0.38461538  0.92307692]
 [-0.92307692  0.38461538]]

Ma trận chuyển vị Q^T:
[[ 0.38461538 -0.92307692]
 [ 0.92307692  0.38461538]]

Kết quả Q^T * Q:
[[ 1. -0.]
 [-0.  1.]]

Q có phải ma trận trực giao không? -> True


###  **3. Giá trị riêng và Véc tơ riêng (Eigenvalues and Eigenvectors)**

- **Định nghĩa:** Cho ma trận vuông $A$. Một số $\lambda$ được gọi là giá trị riêng của $A$, ứng với véc tơ riêng $x \neq 0$, nếu thỏa mãn phương trình:
  $$Ax = \lambda x$$
- **Tính chất ma trận đối xứng:** Nếu $A$ là ma trận vuông đối xứng cấp $k \times k$, nó sẽ có $k$ cặp giá trị riêng và véc tơ riêng $(\lambda_i, e_i)$. Các véc tơ riêng có thể được chuẩn hóa ($e_i'e_i = 1$) và luôn trực giao với nhau ($e_i'e_j = 0$ khi $i \neq j$).

- **Phương trình đặc trưng:** 
Giá trị riêng $\lambda$ thỏa mãn phương trình đặc trưng 
$$det(A - \lambda I) = 0 $$

Sau đó giải phương trình tìm giá trị của $\lambda$ và thay $\lambda$ vào phương trình đặc trưng nhân với vector $X$ và giải ra các giá trị $x_1, x_2, ...., x_n $ là tìm được vector riêng của ma trận

### **4. Dạng toàn phương và Ma trận xác định dương**

- **Dạng toàn phương (Quadratic Form):** Biểu thức có dạng $x'Ax$, trong đó $A$ là ma trận đối xứng.
- **Xác định không âm (Non-negative definite):** Ma trận đối xứng $A$ (hoặc dạng toàn phương tương ứng) là xác định không âm nếu $x'Ax \geq 0$ với mọi véc tơ $x$. Điều này xảy ra khi và chỉ khi mọi giá trị riêng của $A$ đều không âm ($\lambda_i \geq 0$).
- **Xác định dương (Positive definite):** Ma trận đối xứng $A$ là xác định dương nếu $x'Ax > 0$ với mọi véc tơ $x \neq 0$. Điều này tương đương với việc mọi giá trị riêng của $A$ đều dương ($\lambda_i > 0$).
- **Ý nghĩa hình học:** Dạng toàn phương xác định dương $x'Ax$ đại diện cho bình phương của khoảng cách thống kê từ điểm $x$ tới gốc tọa độ. Tập hợp các điểm có khoảng cách hằng số $c$ tạo thành các hình elip (hoặc siêu elip) có độ dài các bán trục tỷ lệ với $1/\sqrt{\lambda_i}$.

#### Exercise 15. Kiểm tra tính đối xứng, giá trị riêng và xác định dương của ma trận

In [5]:
from core.matrix.base import Matrix
from core.matrix.analysis import MatrixAnalysis
A = Matrix([[9, -2],[-2, 6]])
analysis = MatrixAnalysis(A)
print("=" * 60)
print("MATRIX A")
print("=" * 60)
A_T = A.transpose()
is_symmetric = np.allclose(A.data,A_T.data)
print("\nA symmetric:", is_symmetric)

eigenvalues_A = np.linalg.eigvalsh(A.data)
print("Eigenvalues của A:")
for i, value in enumerate(eigenvalues_A, start=1):
    print(f"λ{i} = {value:.6f}")
is_positive_definite = np.all(eigenvalues_A > 0)
print("\nTất cả eigenvalues > 0:",is_positive_definite)
if is_symmetric and is_positive_definite:
    print("\n=> A là positive definite.")
else:
    print("\n=> A không phải positive definite.")

eigenvalues_A, eigenvectors_A = np.linalg.eigh(A.data)
print("Eigenvalues:")
for i, value in enumerate(eigenvalues_A, start=1):
    print(f"λ{i} = {value:.6f}")
print("\nEigenvectors:")
for i in range(len(eigenvalues_A)):
    eigenvalue = eigenvalues_A[i]
    eigenvector = eigenvectors_A[:, i]
    print(f"\nEigenvalue λ{i + 1} = {eigenvalue:.6f}")
    print("Eigenvector:")
    print(eigenvector)

Q = Matrix(eigenvectors_A)
Lambda = Matrix(np.diag(eigenvalues_A))
print(f"Q = {Q}")
print(f"\nΛ = {Lambda}")
print(f"\nQ^T ={Q.transpose()}")
A_reconstructed = (Q@ Lambda@ Q.transpose())
print(f"\nQΛQ^T = {A_reconstructed}")
print("\nKiểm tra A = QΛQ^T:", np.allclose(A.data,A_reconstructed.data))

A_inverse = A.inverse()
print(f"A^(-1) = {A_inverse}")
identity_check = (A@ A_inverse)

print(f"\nA × A^(-1) = {identity_check}")
print("\nKiểm tra bằng Identity:",np.allclose(identity_check.data,np.eye(A.rows)))


eigenvalues_inverse, eigenvectors_inverse = (np.linalg.eigh(A_inverse.data))
print("Eigenvalues của A^(-1):")
for i, value in enumerate(eigenvalues_inverse,start=1):
    print(f"λ{i} = {value:.6f}")
print("\nEigenvectors của A^(-1):")
for i in range(len(eigenvalues_inverse)):
    eigenvalue = eigenvalues_inverse[i]
    eigenvector = eigenvectors_inverse[:, i]
    print(f"\nEigenvalue λ{i + 1} = " 
          f"{eigenvalue:.6f}")
    print(f"Eigenvector:{eigenvector}")

print(f"1 / eigenvalues(A): {1 / eigenvalues_A}")
print(f"\neigenvalues(A^(-1)): {eigenvalues_inverse}")

print("\nKiểm tra:", np.allclose(1 / eigenvalues_A,eigenvalues_inverse))


MATRIX A

A symmetric: True
Eigenvalues của A:
λ1 = 5.000000
λ2 = 10.000000

Tất cả eigenvalues > 0: True

=> A là positive definite.
Eigenvalues:
λ1 = 5.000000
λ2 = 10.000000

Eigenvectors:

Eigenvalue λ1 = 5.000000
Eigenvector:
[-0.4472136  -0.89442719]

Eigenvalue λ2 = 10.000000
Eigenvector:
[-0.89442719  0.4472136 ]
Q = Matrix(
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
)

Λ = Matrix(
[[ 5.  0.]
 [ 0. 10.]]
)

Q^T =Matrix(
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
)

QΛQ^T = Matrix(
[[ 9. -2.]
 [-2.  6.]]
)

Kiểm tra A = QΛQ^T: True
A^(-1) = Matrix(
[[0.12 0.04]
 [0.04 0.18]]
)

A × A^(-1) = Matrix(
[[ 1.00000000e+00 -5.55111512e-17]
 [-2.77555756e-17  1.00000000e+00]]
)

Kiểm tra bằng Identity: True
Eigenvalues của A^(-1):
λ1 = 0.100000
λ2 = 0.200000

Eigenvectors của A^(-1):

Eigenvalue λ1 = 0.100000
Eigenvector:[-0.89442719  0.4472136 ]

Eigenvalue λ2 = 0.200000
Eigenvector:[0.4472136  0.89442719]
1 / eigenvalues(A): [0.2 0.1]

eigenvalues(A^(-1)): [0.1 