<h1 align="center">
    Section 2. Matrix Algebra
</h1>

## **1. Một số khái niệm cơ bản về ma trận** 

#### Các phép tính cơ bản trên ma trận

In [26]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

##### Exercise 11. Matric Multiple
Given 3 matrics A, B, C perform the indicater multiplications:
5A, AB, A.T@A.T, C@B

In [27]:
import numpy as np

A =np.array([[-1, 3],[4, 2]])
B =np.array([[4, -3],[1, -2], [-2, 0]])
C =np.array([[5, -4, 2]])

print(5*A) 
print(B@A)
print(A.T @ B.T)
print(C @ B)

[[-5 15]
 [20 10]]
[[-16   6]
 [ -9  -1]
 [  2  -6]]
[[-16  -9   2]
 [  6  -1  -6]]
[[12 -7]]


##### Exercise 12. Matric Transpose
Verify the following properties of the transpose when A, B, C with: 

$(A^T)^T= A$, $(C^T)^{-1} = (C^{-1})^T$, $(AB)^T=B^T@A^T$

In [28]:
from numpy.linalg import inv
A =np.array([[2, 1], [1, 3]])
B =np.array([[1, 4, 2], [5, 0 ,3]])
C =np.array([[1, 4], [3, 2]])

print(A.T.T == A)
print(inv(C.T))
print(inv(C).T)
print((A @ C).T == C.T @ A.T)

[[ True  True]
 [ True  True]]
[[-0.2  0.3]
 [ 0.4 -0.1]]
[[-0.2  0.3]
 [ 0.4 -0.1]]
[[ True  True]
 [ True  True]]


##### Exercise 17. Matic Determinant
Consider 2 matrices A and B 

These matrices are identical except for a small difference in the (2, 2) position.
Moreover, the columns of A (and B ) are nearly linearly dependent. Show that 
$$A^{-1} = -3*B^{-1}$$
Consequently, small changes-perhaps caused by rounding, cangive substantially different inverses.

In [29]:
A = np.array([[4, 4.001], [4.001, 4.002]], dtype = float)
B = np.array([[4, 4.001], [4.001, 4.002001]], dtype = float)

det_A = np.linalg.det(A) 
det_B = np.linalg.det(B) 

print(det_A, det_B)

-1.0000000051375584e-06 2.999999997644668e-06


### ***1.1. Ma trận trực giao (Orthogonal Matrix)***

- **Định nghĩa:** Một ma trận vuông $Q$ được gọi là ma trận trực giao nếu thỏa mãn điều kiện:
  $$QQ' = Q'Q = I \quad \text{hay} \quad Q' = Q^{-1}$$
- **Tính chất:** Các dòng (hoặc các cột) của ma trận trực giao là các véc tơ có độ dài bằng $1$ (đã chuẩn hóa) và đôi một vuông góc với nhau. Tức là, gọi $q_i$ là dòng thứ $i$, ta có $q_i'q_i = 1$ và $q_i'q_j = 0$ (với $i \neq j$).

##### Exercise 14. Check an matric is is an orthogonal matrix

In [ ]:
Q = np.array([
    [5/13, 12/13],
    [-12/13,  5/13]
])
Q_T = Q.T
product = np.dot(Q_T, Q)

print("Ma trận Q:")
print(Q)
print("\nMa trận chuyển vị Q^T:")
print(Q_T)
print("\nKết quả Q^T * Q:")
print(np.round(product, 8)) 

is_orthogonal = np.allclose(product, np.eye(2))
print(f"\nQ có phải ma trận trực giao không? -> {is_orthogonal}")

Ma trận Q:
[[ 0.38461538  0.92307692]
 [-0.92307692  0.38461538]]

Ma trận chuyển vị Q^T:
[[ 0.38461538 -0.92307692]
 [ 0.92307692  0.38461538]]

Kết quả Q^T * Q:
[[ 1. -0.]
 [-0.  1.]]

Q có phải ma trận trực giao không? -> True


##### Exercise 20. Deteminant of orthogonal matric

In [31]:
np.linalg.det(Q) 

1.0000000000000002

###  **1.2. Giá trị riêng và Véc tơ riêng (Eigenvalues and Eigenvectors)**

- **Định nghĩa:** Cho ma trận vuông $A$. Một số $\lambda$ được gọi là giá trị riêng của $A$, ứng với véc tơ riêng $x \neq 0$, nếu thỏa mãn phương trình:
  $$Ax = \lambda x$$
- **Tính chất ma trận đối xứng:** Nếu $A$ là ma trận vuông đối xứng cấp $k \times k$, nó sẽ có $k$ cặp giá trị riêng và véc tơ riêng $(\lambda_i, e_i)$. Các véc tơ riêng có thể được chuẩn hóa ($e_i'e_i = 1$) và luôn trực giao với nhau ($e_i'e_j = 0$ khi $i \neq j$).

- **Phương trình đặc trưng:** 
Giá trị riêng $\lambda$ thỏa mãn phương trình đặc trưng 
$$det(A - \lambda I) = 0 $$

Sau đó giải phương trình tìm giá trị của $\lambda$ và thay $\lambda$ vào phương trình đặc trưng nhân với vector $X$ và giải ra các giá trị $x_1, x_2, ...., x_n $ là tìm được vector riêng của ma trận

#### **1.2.1. Dạng toàn phương và Ma trận xác định dương**

- **Dạng toàn phương (Quadratic Form):** Biểu thức có dạng $x'Ax$, trong đó $A$ là ma trận đối xứng.
- **Xác định không âm (Non-negative definite):** Ma trận đối xứng $A$ (hoặc dạng toàn phương tương ứng) là xác định không âm nếu $x'Ax \geq 0$ với mọi véc tơ $x$. Điều này xảy ra khi và chỉ khi mọi giá trị riêng của $A$ đều không âm ($\lambda_i \geq 0$).
- **Xác định dương (Positive definite):** Ma trận đối xứng $A$ là xác định dương nếu $x'Ax > 0$ với mọi véc tơ $x \neq 0$. Điều này tương đương với việc mọi giá trị riêng của $A$ đều dương ($\lambda_i > 0$).
- **Ý nghĩa hình học:** Dạng toàn phương xác định dương $x'Ax$ đại diện cho bình phương của khoảng cách thống kê từ điểm $x$ tới gốc tọa độ. Tập hợp các điểm có khoảng cách hằng số $c$ tạo thành các hình elip (hoặc siêu elip) có độ dài các bán trục tỷ lệ với $1/\sqrt{\lambda_i}$.

##### Exercise 15. Matric symmetric and eigenvalues/eigenvectors

In [32]:
from core.matrix.base import Matrix
from core.matrix.analysis import MatrixAnalysis
A = Matrix([[9, -2],[-2, 6]])
analysis = MatrixAnalysis(A)
print("=" * 60)
print("MATRIX A")
print("=" * 60)
A_T = A.transpose()
is_symmetric = np.allclose(A.data,A_T.data)
print("\nA symmetric:", is_symmetric)

eigenvalues_A = np.linalg.eigvalsh(A.data)
print("Eigenvalues của A:")
for i, value in enumerate(eigenvalues_A, start=1):
    print(f"λ{i} = {value:.6f}")
is_positive_definite = np.all(eigenvalues_A > 0)
print("\nTất cả eigenvalues > 0:",is_positive_definite)
if is_symmetric and is_positive_definite:
    print("\n=> A là positive definite.")
else:
    print("\n=> A không phải positive definite.")

eigenvalues_A, eigenvectors_A = np.linalg.eigh(A.data)
print("Eigenvalues:")
for i, value in enumerate(eigenvalues_A, start=1):
    print(f"λ{i} = {value:.6f}")
print("\nEigenvectors:")
for i in range(len(eigenvalues_A)):
    eigenvalue = eigenvalues_A[i]
    eigenvector = eigenvectors_A[:, i]
    print(f"\nEigenvalue λ{i + 1} = {eigenvalue:.6f}")
    print("Eigenvector:")
    print(eigenvector)

Q = Matrix(eigenvectors_A)
Lambda = Matrix(np.diag(eigenvalues_A))
print(f"Q = {Q}")
print(f"\nΛ = {Lambda}")
print(f"\nQ^T ={Q.transpose()}")
A_reconstructed = (Q@ Lambda@ Q.transpose())
print(f"\nQΛQ^T = {A_reconstructed}")
print("\nKiểm tra A = QΛQ^T:", np.allclose(A.data,A_reconstructed.data))

A_inverse = A.inverse()
print(f"A^(-1) = {A_inverse}")
identity_check = (A@ A_inverse)

print(f"\nA × A^(-1) = {identity_check}")
print("\nKiểm tra bằng Identity:",np.allclose(identity_check.data,np.eye(A.rows)))


eigenvalues_inverse, eigenvectors_inverse = (np.linalg.eigh(A_inverse.data))
print("Eigenvalues của A^(-1):")
for i, value in enumerate(eigenvalues_inverse,start=1):
    print(f"λ{i} = {value:.6f}")
print("\nEigenvectors của A^(-1):")
for i in range(len(eigenvalues_inverse)):
    eigenvalue = eigenvalues_inverse[i]
    eigenvector = eigenvectors_inverse[:, i]
    print(f"\nEigenvalue λ{i + 1} = " 
          f"{eigenvalue:.6f}")
    print(f"Eigenvector:{eigenvector}")

print(f"1 / eigenvalues(A): {1 / eigenvalues_A}")
print(f"\neigenvalues(A^(-1)): {eigenvalues_inverse}")

print("\nKiểm tra:", np.allclose(1 / eigenvalues_A,eigenvalues_inverse))


MATRIX A

A symmetric: True
Eigenvalues của A:
λ1 = 5.000000
λ2 = 10.000000

Tất cả eigenvalues > 0: True

=> A là positive definite.
Eigenvalues:
λ1 = 5.000000
λ2 = 10.000000

Eigenvectors:

Eigenvalue λ1 = 5.000000
Eigenvector:
[-0.4472136  -0.89442719]

Eigenvalue λ2 = 10.000000
Eigenvector:
[-0.89442719  0.4472136 ]
Q = Matrix(
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
)

Λ = Matrix(
[[ 5.  0.]
 [ 0. 10.]]
)

Q^T =Matrix(
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
)

QΛQ^T = Matrix(
[[ 9. -2.]
 [-2.  6.]]
)

Kiểm tra A = QΛQ^T: True
A^(-1) = Matrix(
[[0.12 0.04]
 [0.04 0.18]]
)

A × A^(-1) = Matrix(
[[ 1.00000000e+00 -5.55111512e-17]
 [-2.77555756e-17  1.00000000e+00]]
)

Kiểm tra bằng Identity: True
Eigenvalues của A^(-1):
λ1 = 0.100000
λ2 = 0.200000

Eigenvectors của A^(-1):

Eigenvalue λ1 = 0.100000
Eigenvector:[-0.89442719  0.4472136 ]

Eigenvalue λ2 = 0.200000
Eigenvector:[0.4472136  0.89442719]
1 / eigenvalues(A): [0.2 0.1]

eigenvalues(A^(-1)): [0.1 

#### **1.2.2. Phân tích phổ (Spectral Decomposition)**

**Định lý:** Mọi ma trận đối xứng $A$ cấp $k \times k$ đều có thể được phân tích thành tổng của các ma trận dựa trên $k$ cặp giá trị riêng và véc tơ riêng trực chuẩn $(\lambda_i, e_i)$ của nó:
$$A = \sum_{i=1}^{k} \lambda_i e_i e_i' = P \Lambda P'$$
Trong đó:
- $\Lambda$ là ma trận đường chéo chứa các giá trị riêng $\lambda_1, \dots, \lambda_k$.
- $P = [e_1, e_2, \dots, e_k]$ là ma trận trực giao chứa các véc tơ riêng chuẩn hóa.

##### Exercise 16. Spectral Decompsition Analystic

In [39]:
A = np.array([[1, 2], [2, -2]])
eigenvalues_A, eigenvectors_A = np.linalg.eigh(A)
B = np.array([[0, 0], [0, 0]], dtype=float)
for i in range(len(eigenvalues_A)):
    eigenvalue = eigenvalues_A[i]
    eigenvector = eigenvectors_A[:, i]
    print(f"\nEigenvalue λ{i + 1} = {eigenvalue:.6f}")
    print("Eigenvector:")
    print(eigenvector) 

    B += eigenvalue * eigenvector * eigenvector.T
print(B)


Eigenvalue λ1 = -3.000000
Eigenvector:
[-0.4472136   0.89442719]

Eigenvalue λ2 = 2.000000
Eigenvector:
[-0.89442719 -0.4472136 ]
[[ 1. -2.]
 [ 1. -2.]]


##### Exercise 21. Q'AQ and A wiht have the same eigenvalue if Q orthogonal

In [40]:
Q = np.array([
    [5/13, 12/13],
    [-12/13,  5/13]
])
A = np.array([[1, 2], [2, -2]])
res = Q.T @ A @ Q
eigenvalues_res, eigenvectors_res = np.linalg.eigh(A)
for i in range(len(eigenvalues_res)):
    eigenvalue = eigenvalues_res[i]
    eigenvector = eigenvectors_res[:, i]
    print(f"\nEigenvalue λ{i + 1} = {eigenvalue:.6f}")
    print("Eigenvector:")
    print(eigenvector)


Eigenvalue λ1 = -3.000000
Eigenvector:
[-0.4472136   0.89442719]

Eigenvalue λ2 = 2.000000
Eigenvector:
[-0.89442719 -0.4472136 ]


#### **1.2.3. Căn bậc hai của ma trận (Square Root Matrix)**

Sử dụng phân tích phổ cho ma trận xác định dương $A$, ta định nghĩa ma trận căn bậc hai $A^{1/2}$ như sau:
$$A^{1/2} = \sum_{i=1}^{k} \sqrt{\lambda_i} e_i e_i' = P \Lambda^{1/2} P'$$
**Các tính chất cơ bản:**
1. $(A^{1/2})' = A^{1/2}$ (ma trận đối xứng).
2. $A^{1/2}A^{1/2} = A$.
3. Nghịch đảo: $(A^{1/2})^{-1} = \sum_{i=1}^{k} \frac{1}{\sqrt{\lambda_i}} e_i e_i' = P \Lambda^{-1/2} P'$.
4. $A^{1/2}A^{-1/2} = A^{-1/2}A^{1/2} = I$ và $A^{-1/2}A^{-1/2} = A^{-1}$.

In [1]:
# Exercise 27. 
import numpy as np
from scipy.linalg import sqrtm

# 1. Khai báo ma trận A
A = np.array([[9.0, -2.0],
              [-2.0, 6.0]])

print("--- MA TRẬN A ---")
print(A)

# 2. Tính giá trị riêng và vectơ riêng
eigvals, eigvecs = np.linalg.eig(A)
print("\n1. Giá trị riêng:", eigvals)
print("Vectơ riêng chuẩn hóa (các cột của P):\n", eigvecs)

# 3. Tính ma trận căn bậc hai A^(1/2) bằng scipy.linalg.sqrtm
A_half = sqrtm(A)
print("\n2. Ma trận căn bậc hai A^(1/2):\n", A_half)

# 4. Tính ma trận nghịch đảo căn bậc hai A^(-1/2)
A_neg_half = np.linalg.inv(A_half)
print("\n3. Ma trận A^(-1/2):\n", A_neg_half)

# 5. Kiểm tra tính chất
A_reconstructed = A_half @ A_half
identity_check = A_half @ A_neg_half

print("\n4. Kiểm tra A^(1/2) * A^(1/2) == A:")
print(np.allclose(A_reconstructed, A))

print("\n5. Kiểm tra A^(1/2) * A^(-1/2) == I:")
print(np.allclose(identity_check, np.eye(2)))

--- MA TRẬN A ---
[[ 9. -2.]
 [-2.  6.]]

1. Giá trị riêng: [10.  5.]
Vectơ riêng chuẩn hóa (các cột của P):
 [[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]

2. Ma trận căn bậc hai A^(1/2):
 [[ 2.97703572 -0.37048387]
 [-0.37048387  2.42130991]]

3. Ma trận A^(-1/2):
 [[0.34242493 0.05239433]
 [0.05239433 0.42101643]]

4. Kiểm tra A^(1/2) * A^(1/2) == A:
True

5. Kiểm tra A^(1/2) * A^(-1/2) == I:
True


### **1.3. Phân tích giá trị kỳ dị (Singular-Value Decomposition - SVD)**

**Định lý:** Một ma trận thực $A$ bất kỳ cấp $m \times k$ có thể được phân tích thành dạng:
$$A = U \Lambda V'$$
Trong đó:
- $U$ là ma trận trực giao $m \times m$ (các cột là véc tơ riêng của $AA'$).
- $V$ là ma trận trực giao $k \times k$ (các cột là véc tơ riêng của $A'A$).
- $\Lambda$ là ma trận $m \times k$ chứa các **giá trị kỳ dị** $\lambda_i \geq 0$ (là căn bậc hai của các giá trị riêng khác không của $AA'$ hoặc $A'A$) trên đường chéo chính.
*Ứng dụng SVD:* Dùng để tìm xấp xỉ bình phương tối thiểu hạng $s$ của một ma trận $A$ (Định lý Eckart-Young).

In [2]:
# Exercise 28. 
import numpy as np

# 1. Khai báo ma trận A
A = np.array([[1.0, 1.0],
              [2.0, -2.0],
              [2.0, 2.0]])

# 2. Tính A^T * A và AA^T
AtA = A.T @ A
AAt = A @ A.T

print("A^T * A:\n", AtA)
print("\nA * A^T:\n", AAt)

# 3. Tính giá trị riêng và véc-tơ riêng của A^T * A
eigvals_AtA, eigvecs_AtA = np.linalg.eig(AtA)
print("\nGiá trị riêng của A^T * A:", eigvals_AtA)
print("Véc-tơ riêng của A^T * A:\n", eigvecs_AtA)

# 4. Phân tích SVD bằng numpy.linalg.svd
U, S, Vt = np.linalg.svd(A, full_matrices=True)

print("\n--- KẾT QUẢ SVD ---")
print("Ma trận U (3x3):\n", U)
print("Các giá trị kỳ dị S (Singular Values):", S)
print("Ma trận V^T (2x2):\n", Vt)

# 5. Kiểm tra tính chính xác bằng cách tái tạo lại ma trận A
Sigma = np.zeros((3, 2))
np.fill_diagonal(Sigma, S)
A_reconstructed = U @ Sigma @ Vt

print("\nMa trận A tái tạo từ U * Sigma * V^T:\n", A_reconstructed)

A^T * A:
 [[9. 1.]
 [1. 9.]]

A * A^T:
 [[2. 0. 4.]
 [0. 8. 0.]
 [4. 0. 8.]]

Giá trị riêng của A^T * A: [10.  8.]
Véc-tơ riêng của A^T * A:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

--- KẾT QUẢ SVD ---
Ma trận U (3x3):
 [[-4.47213595e-01 -5.38225632e-17 -8.94427191e-01]
 [-1.10334851e-16 -1.00000000e+00  5.55111512e-17]
 [-8.94427191e-01  2.34599916e-18  4.47213595e-01]]
Các giá trị kỳ dị S (Singular Values): [3.16227766 2.82842712]
Ma trận V^T (2x2):
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

Ma trận A tái tạo từ U * Sigma * V^T:
 [[ 1.  1.]
 [ 2. -2.]
 [ 2.  2.]]


### **1.4. Véc tơ và Ma trận ngẫu nhiên**

- **Định nghĩa:** Véc tơ (hoặc ma trận) ngẫu nhiên là véc tơ (hoặc ma trận) mà mỗi phần tử bên trong nó là một biến ngẫu nhiên.
- **Kỳ vọng Toán học:** Giá trị kỳ vọng $E(X)$ của ma trận ngẫu nhiên $X$ là một ma trận gồm các giá trị kỳ vọng của từng phần tử tương ứng.
- **Tính chất Kỳ vọng:**
  $$E(X + Y) = E(X) + E(Y)$$
  $$E(AXB) = A E(X) B \quad \text{(với A, B là các ma trận hằng số)}$$

### **1.5. Véc tơ trung bình, Ma trận hiệp phương sai và Tương quan**

Cho véc tơ ngẫu nhiên $X = [X_1, X_2, \dots, X_p]'$.
- **Véc tơ trung bình:** $\mu = E(X) = [\mu_1, \mu_2, \dots, \mu_p]'$.
- **Ma trận hiệp phương sai:** 
  $$\Sigma = E[(X - \mu)(X - \mu)'] = \text{Cov}(X)$$
  $\Sigma$ là ma trận đối xứng $p \times p$, phần tử trên đường chéo là phương sai $\sigma_{ii}$, phần tử ngoài đường chéo là hiệp phương sai $\sigma_{ik}$. Ma trận $\Sigma$ luôn xác định không âm.
- **Sự độc lập:** Hai biến $X_i, X_k$ độc lập thì hiệp phương sai $\sigma_{ik} = 0$. Hai véc tơ ngẫu nhiên $X^{(1)}, X^{(2)}$ độc lập thì $\text{Cov}(X^{(1)}, X^{(2)}) = 0$. (Lưu ý chiều ngược lại chưa chắc đúng).
- **Ma trận tương quan:** Hệ số tương quan $\rho_{ik} = \frac{\sigma_{ik}}{\sqrt{\sigma_{ii}\sigma_{kk}}}$. Ma trận hệ số tương quan $\rho$ có liên hệ với $\Sigma$ qua:
  $$\Sigma = V^{1/2} \rho V^{1/2} \quad \text{và} \quad \rho = V^{-1/2} \Sigma V^{-1/2}$$
  (Với $V^{1/2}$ là ma trận đường chéo chứa các độ lệch chuẩn $\sqrt{\sigma_{ii}}$).

In [3]:
# Exercise 40
import numpy as np
import pandas as pd

# Tạo DataFrame chứa dữ liệu
data = {'X1': [10, 5, 20, 8], 'X2': [20, 15, 12, 17]}
df = pd.DataFrame(data)

# 1. Vector trung bình mẫu
mean_vec = df.mean().to_numpy().reshape(-1, 1)
print("Vector trung bình x_bar:")
print(mean_vec)

# 2. Ma trận phương sai - hiệp phương sai mẫu S (ddof=1 tương ứng chia n-1)
S = df.cov().to_numpy()
print("\nMa trận hiệp phương sai S:")
print(S)

# 3. Ma trận hệ số tương quan R
# Cách 1: Dùng trực tiếp hàm corr()
R = df.corr().to_numpy()
print("\nMa trận tương quan R (dùng corr):")
print(R)

# Cách 2: Dùng công thức R = (V^(1/2))^(-1) * S * (V^(1/2))^(-1)
V_sqrt = np.diag(np.sqrt(np.diag(S)))
V_sqrt_inv = np.linalg.inv(V_sqrt)
R_calc = V_sqrt_inv @ S @ V_sqrt_inv
print("\nMa trận tương quan R (tính qua V^(-1/2) * S * V^(-1/2)):")
print(R_calc)

Vector trung bình x_bar:
[[10.75]
 [16.  ]]

Ma trận hiệp phương sai S:
[[ 42.25       -12.33333333]
 [-12.33333333  11.33333333]]

Ma trận tương quan R (dùng corr):
[[ 1.         -0.56362245]
 [-0.56362245  1.        ]]

Ma trận tương quan R (tính qua V^(-1/2) * S * V^(-1/2)):
[[ 1.         -0.56362245]
 [-0.56362245  1.        ]]


### **1.6. Tổ hợp tuyến tính của các Véc tơ ngẫu nhiên**

Khi chuyển đổi véc tơ ngẫu nhiên $X$ qua phép biến đổi tuyến tính $Z = CX$ (với $C$ là ma trận hằng số $q \times p$):
- **Véc tơ trung bình mới:** 
  $$\mu_Z = E(Z) = C \mu_X$$
- **Ma trận hiệp phương sai mới:** 
  $$\Sigma_Z = \text{Cov}(Z) = C \Sigma_X C'$$

Tương tự, đối với 2 biến đổi tuyến tính $Z_1 = CX$ và $Z_2 = DX$, ma trận hiệp phương sai chéo giữa chúng là:
$$\text{Cov}(Z_1, Z_2) = C \Sigma_X D'$$

### **1.7. Phân hoạch Véc tơ và Ma trận (Partitioning)**

Khi chia véc tơ ngẫu nhiên $X$ thành hai tập con $X^{(1)}$ và $X^{(2)}$, ta có thể phân hoạch các đặc trưng thống kê tương ứng:
- **Véc tơ trung bình:**
  $$\mu = \begin{bmatrix} \mu^{(1)} \\ \mu^{(2)} \end{bmatrix}$$
- **Ma trận hiệp phương sai:**
  $$\Sigma = \begin{bmatrix} \Sigma_{11} & \Sigma_{12} \\ \Sigma_{21} & \Sigma_{22} \end{bmatrix}$$
  Trong đó, $\Sigma_{11}$ là ma trận hiệp phương sai của $X^{(1)}$, $\Sigma_{22}$ là của $X^{(2)}$, và $\Sigma_{12} = \Sigma_{21}'$ là ma trận hiệp phương sai chéo giữa $X^{(1)}$ và $X^{(2)}$.
  *Ghi chú:* Việc phân hoạch này cũng áp dụng tương tự cho các thống kê mẫu (Sample mean vector $\bar{x}$ và Sample covariance matrix $S$).

In [4]:
# Exercise 36

import numpy as np

# Khai báo vector trung bình và ma trận hiệp phương sai tổng
mu_X = np.array([4, 3, 2, 1])
Sigma_X = np.array([
    [3, 0, 2, 2],
    [0, 1, 1, 0],
    [2, 1, 9, -2],
    [2, 0, -2, 4]
])

# Phân hoạch các thành phần
mu1 = mu_X[:2]
mu2 = mu_X[2:]

Sigma11 = Sigma_X[:2, :2]
Sigma22 = Sigma_X[2:, 2:]
Sigma12 = Sigma_X[:2, 2:]

# Khai báo ma trận biến đổi A và B
A = np.array([[1, 2]])
B = np.array([[1, -2], [2, -1]])

# 1. Kỳ vọng và Phương sai của Y1 = AX(1)
E_Y1 = A @ mu1
Cov_Y1 = A @ Sigma11 @ A.T

print(f"E(AX(1)): {E_Y1[0]}")
print(f"Var(AX(1)): {Cov_Y1[0, 0]}")

# 2. Hiệp phương sai của Y2 = BX(2)
Cov_Y2 = B @ Sigma22 @ B.T
print("\nCov(BX(2)):")
print(Cov_Y2)

# 3. Hiệp phương sai giữa AX(1) và BX(2)
Cov_AX1_BX2 = A @ Sigma12 @ B.T
print("\nCov(AX(1), BX(2)):")
print(Cov_AX1_BX2)

E(AX(1)): 10
Var(AX(1)): 7

Cov(BX(2)):
[[33 36]
 [36 48]]

Cov(AX(1), BX(2)):
[[0 6]]
