<h1 align="center">
    Section 2. Matrix Algebra
</h1>

## **1. Một số khái niệm cơ bản về ma trận** 

### ***1.1. Hệ vector độc lập và phụ thuộc tuyến tính***

- **Định nghĩa:** Một ma trận vuông $Q$ được gọi là ma trận trực giao nếu thỏa mãn điều kiện:
  $$QQ' = Q'Q = I \quad \text{hay} \quad Q' = Q^{-1}$$
- **Tính chất:** Các dòng (hoặc các cột) của ma trận trực giao là các véc tơ có độ dài bằng $1$ (đã chuẩn hóa) và đôi một vuông góc với nhau. Tức là, gọi $q_i$ là dòng thứ $i$, ta có $q_i'q_i = 1$ và $q_i'q_j = 0$ (với $i \neq j$).

In [1]:
import numpy as np

# Khai báo ma trận Q
sqrt2_div_2 = np.sqrt(2) / 2
Q = np.array([
    [sqrt2_div_2, -sqrt2_div_2],
    [sqrt2_div_2,  sqrt2_div_2]
])

# Tính Q_T * Q
Q_T = Q.T
product = np.dot(Q_T, Q)

# In kết quả
print("Ma trận Q:")
print(Q)
print("\nMa trận chuyển vị Q^T:")
print(Q_T)
print("\nKết quả Q^T * Q:")
print(np.round(product, 8)) # Làm tròn để tránh sai số số thực

# Kiểm tra điều kiện ma trận đơn vị
is_orthogonal = np.allclose(product, np.eye(2))
print(f"\nQ có phải ma trận trực giao không? -> {is_orthogonal}")

Ma trận Q:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Ma trận chuyển vị Q^T:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Kết quả Q^T * Q:
[[ 1. -0.]
 [-0.  1.]]

Q có phải ma trận trực giao không? -> True


###  **3. Giá trị riêng và Véc tơ riêng (Eigenvalues and Eigenvectors)**

- **Định nghĩa:** Cho ma trận vuông $A$. Một số $\lambda$ được gọi là giá trị riêng của $A$, ứng với véc tơ riêng $x \neq 0$, nếu thỏa mãn phương trình:
  $$Ax = \lambda x$$
- **Tính chất ma trận đối xứng:** Nếu $A$ là ma trận vuông đối xứng cấp $k \times k$, nó sẽ có $k$ cặp giá trị riêng và véc tơ riêng $(\lambda_i, e_i)$. Các véc tơ riêng có thể được chuẩn hóa ($e_i'e_i = 1$) và luôn trực giao với nhau ($e_i'e_j = 0$ khi $i \neq j$).

- **Phương trình đặc trưng:** 
Giá trị riêng $\lambda$ thỏa mãn phương trình đặc trưng 
$$det(A - \lambda I) = 0 $$

Sau đó giải phương trình tìm giá trị của $\lambda$ và thay $\lambda$ vào phương trình đặc trưng nhân với vector $X$ và giải ra các giá trị $x_1, x_2, ...., x_n $ là tìm được vector riêng của ma trận

In [1]:
import numpy as np

# Khai báo ma trận A
A = np.array([
    [3.0, 1.0],
    [1.0, 3.0]
])

# Tính giá trị riêng và véc-tơ riêng bằng numpy.linalg.eigh (dành cho ma trận đối xứng)
eigenvalues, eigenvectors = np.linalg.eigh(A)

print("--- KẾT QUẢ ---")
for i in range(len(eigenvalues)):
    print(f"\nCặp giá trị/véc-tơ riêng thứ {i+1}:")
    print(f"  Giá trị riêng λ_{i+1} = {eigenvalues[i]}")
    print(f"  Véc-tơ riêng chuẩn hóa e_{i+1} = {eigenvectors[:, i]}")

# Kiểm tra A * e = λ * e
e1 = eigenvectors[:, 0]
lambda1 = eigenvalues[0]
print("\nKiểm tra A * e1:", np.dot(A, e1))
print("Kiểm tra λ1 * e1:", lambda1 * e1)

--- KẾT QUẢ ---

Cặp giá trị/véc-tơ riêng thứ 1:
  Giá trị riêng λ_1 = 2.0
  Véc-tơ riêng chuẩn hóa e_1 = [-0.70710678  0.70710678]

Cặp giá trị/véc-tơ riêng thứ 2:
  Giá trị riêng λ_2 = 4.0
  Véc-tơ riêng chuẩn hóa e_2 = [0.70710678 0.70710678]

Kiểm tra A * e1: [-1.41421356  1.41421356]
Kiểm tra λ1 * e1: [-1.41421356  1.41421356]
